CREATE TABLE  "HIERARCHY" 
(
  "AGENT_CODE" CHAR(6) NOT NULL REFERENCES AGENTS,
  "MANAGER_CODE" CHAR(6) REFERENCES AGENTS
);

INSERT INTO HIERARCHY VALUES ('A001',NULL);
INSERT INTO HIERARCHY VALUES ('A015',NULL);
INSERT INTO HIERARCHY VALUES ('A009',NULL);
INSERT INTO HIERARCHY VALUES ('A007',NULL);
INSERT INTO HIERARCHY VALUES ('A002','A001');
INSERT INTO HIERARCHY VALUES ('A003','A001');
INSERT INTO HIERARCHY VALUES ('A004','A001');
INSERT INTO HIERARCHY VALUES ('A005','A003');
INSERT INTO HIERARCHY VALUES ('A006','A005');
INSERT INTO HIERARCHY VALUES ('A010','A007');
INSERT INTO HIERARCHY VALUES ('A008','A007');
INSERT INTO HIERARCHY VALUES ('A011','A007');
INSERT INTO HIERARCHY VALUES ('A012','A008');



